# Generated by Django 5.0 on 2024-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module1", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_value", models.FloatField()),
                ("y_value", models.FloatField()),
            ],
        ),
    ]
