# Generated by Django 5.0 on 2024-02-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module1", "0003_graphdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphData",
        ),
    ]
